name: CI

on:
  push:
  pull_request:

env:
  NODE_VERSION: 16

jobs:
  lint:
    name: Run Eslint And Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

      - name: Code Formatting
        run: npm run format

  tsc:
    name: Check Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npx tsc